---
image:
  file: .gitpod.dockerfile

tasks:
  - name: initialize
    init: |

      # ------------------------------------
      # golang & tinygo
      # ------------------------------------
      echo "👋 installing gvm" 
      bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
      source /home/gitpod/.gvm/scripts/gvm
      echo "👋 installing go 1.16" 
      gvm install go1.16 -B
      gvm use go1.16
      echo "👋 get go dependencies"
      go get -v -t -d ./...

      echo "👋 installing tinygo 0.19.0"
      wget https://github.com/tinygo-org/tinygo/releases/download/v0.19.0/tinygo_0.19.0_amd64.deb
      sudo dpkg -i tinygo_0.19.0_amd64.deb
      rm tinygo_0.19.0_amd64.deb
      export PATH=$PATH:/usr/local/tinygo/bin
      tinygo version

      #go get github.com/wasmerio/wasmer-go/wasmer

      # ------------------------------------
      # RustLang
      # ------------------------------------
      curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # ------------------------------------
      # wasmer
      # ------------------------------------
      curl https://get.wasmer.io -sSfL | sh
      source /home/gitpod/.wasmer/wasmer.sh

      # ------------------------------------
      # grain
      # ------------------------------------
      (echo 'export PATH="${PATH}:$(yarn global bin)"' >> ~/.bashrc) && source ~/.bashrc

      # ------------------------------------
      # fastify
      # ------------------------------------
      npm install

      sudo apt install httpie -y

      # ------------------------------------
      # hey
      # ------------------------------------
      wget https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64
      chmod +x hey_linux_amd64
      sudo cp hey_linux_amd64 /usr/bin/hey
      rm hey_linux_amd64

      clear
      gp sync-done prerequisites


  - name: functions
    init: gp sync-await prerequisites
    command: |
      source /home/gitpod/.wasmer/wasmer.sh 
      (echo 'export PATH="${PATH}:$(yarn global bin)"' >> ~/.bashrc) && source ~/.bashrc
      cd functions
      clear

  - name: src
    init: gp sync-await prerequisites
    command: |
      source /home/gitpod/.wasmer/wasmer.sh 
      (echo 'export PATH="${PATH}:$(yarn global bin)"' >> ~/.bashrc) && source ~/.bashrc
      cd src
      clear

ports:
  - port: 8080
    visibility: public

vscode:
  extensions:
    - golang.go
    - wayou.vscode-todo-highlight
    - coenraads.bracket-pair-colorizer-2
    - pkief.material-icon-theme
    - rust-lang.rust
    - marp-team.marp-vscode@1.3.0
    - grain-lang.vscode-grain
    - johnpapa.vscode-peacock
