---
image:
  file: .gitpod.dockerfile

tasks:
  - name: initialize
    init: |
      # ------------------------------------
      # wasmer
      # ------------------------------------
      curl https://get.wasmer.io -sSfL | sh
      source /home/gitpod/.wasmer/wasmer.sh

      # ------------------------------------
      # grain
      # ------------------------------------
      (echo 'export PATH="${PATH}:$(yarn global bin)"' >> ~/.bashrc) && source ~/.bashrc

      # ------------------------------------
      # fastify
      # ------------------------------------
      npm install

      sudo apt install httpie -y

      # ------------------------------------
      # hey
      # ------------------------------------
      wget https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64
      chmod +x hey_linux_amd64
      sudo cp hey_linux_amd64 /usr/bin/hey

      clear
      gp sync-done prerequisites


  - name: functions
    init: gp sync-await prerequisites
    command: |
      source /home/gitpod/.wasmer/wasmer.sh 
      (echo 'export PATH="${PATH}:$(yarn global bin)"' >> ~/.bashrc) && source ~/.bashrc
      cd functions
      clear

  - name: src
    init: gp sync-await prerequisites
    command: |
      source /home/gitpod/.wasmer/wasmer.sh 
      (echo 'export PATH="${PATH}:$(yarn global bin)"' >> ~/.bashrc) && source ~/.bashrc
      cd src
      clear

ports:
  - port: 8080
    visibility: public

vscode:
  extensions:
    - wayou.vscode-todo-highlight
    - coenraads.bracket-pair-colorizer-2
    - pkief.material-icon-theme
    - rust-lang.rust
    - marp-team.marp-vscode@1.3.0
    - grain-lang.vscode-grain
    - johnpapa.vscode-peacock
